### ISSUE TITLE
ToSPQuery bug with ViewFields

### ISSUE THREAD

**Issue by RFlipper** [andrei-markeev/camljs-console#1]
Hello Andrei, 

Firstly thank you for great tool which is really helps improve productivity. 
I have noticed a small bug in [FinalizeToSPQuery method](https://github.com/andrei-markeev/camljs-console/blob/master/Scripts/camljs.js#L921), if you specify view fields it generates wrong CAML query.

**Comment by andrei-markeev** [comment]
Yeah, you're right, thanks for reporting this! :+1: I'll fix it ASAP.

**Comment by andrei-markeev** [comment]
was fixed looong ago (https://github.com/andrei-markeev/camljs/commit/5a94c6e2f6743f8bedc521c3ccb84317ad6b59cf), sorry forgot to update this issue
