### ISSUE TITLE
Intellisense has stopped working

### ISSUE THREAD

**Issue by WoHuy** [andrei-markeev/camljs-console#10]
I still use this extension from time to time and it has always performed flawlesly.

A few weeks ago, however, intellisense has stopped working. I can still run queries and get live data like below, but I need to type them manually.
![image](https://user-images.githubusercontent.com/48773525/143414847-f7698d67-7f36-4d19-a213-57e042d6a752.png)

I am experiencing this issue on SharePoint 2013/2016/2019 using Google Chrome 96.0.4664.45.

Any ideas on how to solve this?

**Comment by andrei-markeev** [comment]
hey! I released a new version of CamlJs console, 1.0.17, recently (~2 weeks ago). It could have broken the intellisense... I'll check over the weekend. Thanks for reporting!

**Comment by WoHuy** [comment]
Hi Andrei!
Did you get a chance to look at this issue already?
Thanks!

**Comment by philbeauchamp** [comment]
I was having luck with this still working until very recently where the intellisense has stopped working for me too!  In Edge and Chrome, neither provides intellisense.  I love this tool and it helps my create queries, but the intellisense is one of the greatest features for me to do it quickly.  Thanks for any work you can do to help fix this bug.  Thanks for a great tool.

**Comment by andrei-markeev** [comment]
hey guys, unfortunately I was not able to fix it yet... I will look into it right now.

**Comment by andrei-markeev** [comment]
I think I fixed it. At least locally, it works. But it will take some time for the extension to be published. They now review every update manually, "which can take several weeks" (hopefully not).

**Comment by andrei-markeev** [comment]
will be fixed in 1.0.18, as soon as it gets published: let's reopen if the fix doesn't work for some reason. sorry once again for the inconvenience! 🙏

**Comment by andrei-markeev** [comment]
ok guys, the update got published and it seems to work fine. to get the latest version, press "Update" button:
![image](https://user-images.githubusercontent.com/5181724/155697272-a699c5e4-56fd-4fb1-9535-fa6e61ee589b.png)

**Comment by WoHuy** [comment]
Hi Andrei, just to confirm that intellisense works again as expected!

Thanks a million for fixing this, my life just got a lot easier :-)
Wouter
