### ISSUE TITLE
Operation is not valid due to the current state of the object

### ISSUE THREAD

**Issue by xguitoux** [andrei-markeev/camljs-console#3]
Issue moved to camljs project (seems more relevant)
https://camljs.codeplex.com/workitem/11

**Comment by andrei-markeev** [comment]
Hi,

There seems to be some sort of bug with this particular query, Camljs returns empty string.

You can use just `new CamlBuilder().View().ToString();` instead, or if ordering is necessary, try with a dummy condition, e.g.:
```js
new CamlBuilder().View().Query()
	.Where().CounterField("ID").IsNotNull()
	.OrderBy("ID").ToString();
```

Sorry for inconvenience! I'll try to fix it asap.

**Comment by xguitoux** [comment]
Working like a charm, a bit strange but working, Thanks
