### ISSUE TITLE
Support for <Today /> with Date Fields

### ISSUE THREAD

**Issue by andikrueger** [andrei-markeev/camljs-console#4]
I'm trying to create a query with Date Fields and want to use the Today Element. Is there support for that or any workaround available?
See:
https://msdn.microsoft.com/de-de/library/office/ms460496.aspx

**Comment by andrei-markeev** [comment]
Yes, it's supported via CamlBuilder.CamlValues.Today.
TodayWithOffset is also available.

![image](https://user-images.githubusercontent.com/5181724/27399988-60ff0c32-56c7-11e7-808e-687b2ae5aff1.png)

**Comment by andikrueger** [comment]
Thank you for the quick response.
