### ISSUE TITLE
Query not being translated into CAML

### ISSUE THREAD

**Issue by WoHuy** [andrei-markeev/camljs-console#7]
Dear Andrei,

The update to version 1.0.15 fixed this intellisense [issue](https://github.com/andrei-markeev/camljs-console/issues/6) (thanks!), however my queries are no longer translated into CAML.
![image](https://user-images.githubusercontent.com/48773525/68304638-75413400-00a6-11ea-8af9-df600788985b.png)
In the HTTP POST request payload, I find that no query is sent: `&lt;Query&gt;[object Object]&lt;/Query&gt;`

**Comment by WoHuy** [comment]
Not sure if it is related to the above, but I notice that the same HTTP POST request payload states:
`<Request xmlns="http://schemas.microsoft.com/sharepoint/clientquery/2009" SchemaVersion="15.0.0.0" LibraryVersion="16.0.0.0" ApplicationName="Javascript Library">`

Whereas the response states
`"SchemaVersion":"15.0.0.0","LibraryVersion":"16.0.4756.1000"`

**Comment by andrei-markeev** [comment]
ouch, that's like very strange, I don't think I had any changes related to this 🤔

**Comment by WoHuy** [comment]
Andrei,
This morning I opened up an Incognito window ran the same query ---> it created the CAML and returned the expected result.
So I believe the issue must have been somehow cache related.
You may close the ticket.
